spring.datasource.url = jdbc:mysql://localhost:3306/springbootApp?useSSL=false
#spring.datasource.url = jdbc:mysql://localhost:3306/spring7?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=gauravk700

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.properties.hibernate.datasource.show_sql = true
#spring.datasource..format_sql = true
#spring.jpa.hibernate.ddl-auto = create
spring.jpa.hibernate.ddl-auto = update

#security.basic.enabled=false

server.port=8082
spring.security.user.name=gaurav
spring.security.user.password=gauravk700
